### PR TITLE
Update raspiwrite.py

### PR DESCRIPTION
**Pull request by thecodenomad**
Missing colon on else statement at 177, and missing indentation at 275 & 278.

### CODE REVIEW

**Comment by ingalls** [comment]
This definitely needs to be added! It currently breaks the program

**Comment by hbast** [comment]
that's right. here's the console output

mac-mini:wheezy-offical holger$ sudo ./raspiwrite.py 
  File "./raspiwrite.py", line 177
    else
       ^
SyntaxError: invalid syntax

**Comment by ingalls** [comment]
@rrgomez the patch works perfectly and thanks for submitting it.. Now I just wish it would get pulled...

**Comment by lolsborn** [comment]
+1 for this patch.  I expect Alpha software to have some bugs, but you should at least try to run the thing before pushing upstream.

**Pull request closed without merging**
